name: Daily Streak Commit

on:
  schedule:
    - cron: "0 5 * * *"   # Every day at 5 AM UTC
  workflow_dispatch:

permissions:
  contents: write   # ✅ This is required to allow commits

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update log file
        run: echo "$(date)" >> log.txt

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add log.txt
          git commit -m "Daily streak update" || echo "No changes to commit"
          git push
